### ISSUE TITLE
TypeError: Cannot read private member #renewalDate from an object whose class did not declare it

### ISSUE THREAD

**Issue by wmurphyrd** [small-tech/auto-encrypt#4]
Hi Aral! Loving auto-encrypt.

I see a bunch of these in my error logs: 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read private member #renewalDate from an object whose class did not declare it
at Timeout.checkForRenewal [as _onTimeout] (/home/ubuntu/immers/node_modules/@small-tech/auto-encrypt/lib/Certificate.js:317:40)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
```

@small-tech/auto-encrypt@2.0.6 
node --version: v14.15.4

**Comment by wmurphyrd** [comment]
This is resolved in the latest verion
